#pragma once

/*
Struct that contains all information about the simulation parameters, each struct is passed to every process:

	width/length - size of the simulation area in meters
	numberPeople - number of people inside the simulation
	numberCars - number of cars inside the simulation
	noisePerPerson - noise generated by a single person
	noisePerCar - noise generated by a single car
	distanceAffectPeople - distance in meters affected by the noise of people
	distanceAffectCar - distance in meters affected by the noise of car
	movingSpeedPeople - moving speed in meter per second of the people inside the simulation
	movingSpeedCar - moving speed in meter per second of the cars inside the simulation
	timeStep - time in second before the simulation is re-calculated
	rank - rank of the process that is running the simulation
	size - number of process to run
	granularity - size of the portion of area that is averaged. Non-limiting assumption: the width and length of the 
					area is a multiple of the granularity
	latitude/longitude - coordinates of the area starting from the upper left corner of the area

*/

struct simulationParameters {
	int width;
	int length;
	int numberPeople;
	int numberCars;
	int noisePerPerson;
	int noisePerCar;
	int distanceAffectPeople;
	int distanceAffectCar;
	double movingSpeedPeople;
	double movingSpeedCar;
	int timeStep;
	int rank;
	int size;
	int granularity;
	double latitude;
	double longitude;
};
